modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="fasterflyblockbreak" #mandatory
version="1.20.1-1.0.0" #mandatory
displayName="Faster Fly Block Breaking" #mandatory
credits="Barteks2x" #optional
authors="Rinko1231" #optional
description="An unofficially port of Fast Fly Block Breaking by Rinko1231. You can change the speed in config."
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.fasterflyblockbreak]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fasterflyblockbreak]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
